### ISSUE TITLE
Cant create new migration using generate-migration command

### ISSUE THREAD

**Issue by antonvas** [mongrate/mongrate-bundle#10]
When I trying to run `php app/console mongrate:generate-migration MigrationName` recieving:

```
[UnexpectedValueException]
DirectoryIterator::__construct(resources/migration-template/): failed to open dir: No such file or directory
```

**Comment by amyboyd** [comment]
Have you configured your Symfony application's config.yml? It should look something like:

```
mongrate:
    mongodb_server: 'mongodb://localhost:27017'
    mongodb_db: my_database
    migrations_directory: "%kernel.root_dir%/../migrations"
```

(Replacements from `parameters.yml` also can be used)
